apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: nginx-service
spec:
 selector:
   # Selector for Pods
   app: nginx
 ports:
   # Port Map
 - port: 1337
   targetPort: 80
   protocol: TCP
 type: LoadBalancer
